### PR TITLE
[Modules/Forum] Fix 500 Internal Server error on reply

### PR DESCRIPTION
**Pull request by DuelistRag3**
## Description

adjust controller function call to match the actuell model function

## Motivation and Context

Replys couldn´t be created

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pangolp** [comment]
Hi, Thanks for the input, how can I test the change? I mean, currently in the code, is there any error? How can I reproduce it?

**Comment by DuelistRag3** [comment]
> 
> 
> Hi, Thanks for the input, how can I test the change? I mean, currently in the code, is there any error? How can I reproduce it?

In theory just try to comment on a forum thread, i encountered that issue while trying to reply to a forum thread ^^

**Comment by DuelistRag3** [comment]
> 
> 
> > Hi, Thanks for the input, how can I test the change? I mean, currently in the code, is there any error? How can I reproduce it?
> 
> In theory just try to comment on a forum thread, i encountered that issue while trying to reply to a forum thread ^^

As far as i know, the delete comment function is also bugged (non existent), i think i already fixed that to, let me do a quick look

**Comment by pangolp** [comment]
That's fine with me then. I will try to reproduce the problem. As for the delete function you mention, please make the change in another PR. Because this one I hope to merge it soon. I need to test it first.

**Comment by pangolp** [comment]
Currently, before applying the PR, when creating a response, no action is taken. However, if I apply the PR, an error occurs but for another function. Can you reproduce this problem as well or do you not have it?

```
An uncaught Exception was encountered
Type: Error
Message: Call to undefined method Forum_model::getCountPostAuthor()
Filename: D:\xampp\htdocs\blizzcms\application\modules\forum\views\topic.php
Line Number: 64
```

**Comment by pangolp** [comment]
That method mentioned in the error, I looked it up in the model, and it does not exist. We could apply this pull request and then make another one, running the bug. In fact, I'm going to do that. I will apply this change, and add a pull request, to correct the error. Thanks for the input.

**Comment by DuelistRag3** [comment]
> 
> 
> Currently, before applying the PR, when creating a response, no action is taken. However, if I apply the PR, an error occurs but for another function. Can you reproduce this problem as well or do you not have it?
> 
> ```
> An uncaught Exception was encountered
> Type: Error
> Message: Call to undefined method Forum_model::getCountPostAuthor()
> Filename: D:\xampp\htdocs\blizzcms\application\modules\forum\views\topic.php
> Line Number: 64
> ```

Hmm no i wasnt able to reproduce this error

**Comment by pangolp** [comment]
> > Currently, before applying the PR, when creating a response, no action is taken. However, if I apply the PR, an error occurs but for another function. Can you reproduce this problem as well or do you not have it?
> > ```
> > An uncaught Exception was encountered
> > Type: Error
> > Message: Call to undefined method Forum_model::getCountPostAuthor()
> > Filename: D:\xampp\htdocs\blizzcms\application\modules\forum\views\topic.php
> > Line Number: 64
> > ```
> 
> Hmm no i wasnt able to reproduce this error

Hai aggiornato il CMS? Perché ho appena applicato la correzione, dopo aver approvato la tua domanda, forse è per questo che non sei riuscito a riprodurlo. Questo è il PR che ho fatto dopo aver approvato il tuo: https://github.com/WoW-CMS/BlizzCMS/pull/24

**Pull request merged**
